- name: First time setup of OpenNIC on server
  hosts: opennic
  remote_user: root # update if using become
  ## Use become by uncommenting the lines below to elevate once reaching the server
  # become: yes
  # become_user: root
  # become_method: sudo

  # Roles for different OS
  roles:
  - { role: centos, when: ansible_distribution == "CentOS" and ansible_distribution_major_version in CENTOS_VERSIONS}
  - { role: fedora, when: ansible_distribution == "Fedora" and ansible_distribution_major_version in FEDORA_VERSIONS}
  - { role: ubuntu, when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version in UBUNTU_VERSIONS}
  - { role: debian, when: ansible_distribution == "Debian" and ansible_distribution_major_version in DEBIAN_VERSIONS}
